/*

  KernelPatchDll.H

  Author: <your name>
  Last Updated: 2006-02-12

  This framework is generated by EasySYS 0.3.0
  This template file is copying from QuickSYS 0.3.0 written by Chunhua Liu

*/

#ifndef _KERNELPATCHDLL_H
#define _KERNELPATCHDLL_H 1

//
// Define the various device type values.  Note that values used by Microsoft
// Corporation are in the range 0-0x7FFF(32767), and 0x8000(32768)-0xFFFF(65535)
// are reserved for use by customers.
//

#define FILE_DEVICE_KERNELPATCHDLL	0x8000

//
// Macro definition for defining IOCTL and FSCTL function control codes. Note
// that function codes 0-0x7FF(2047) are reserved for Microsoft Corporation,
// and 0x800(2048)-0xFFF(4095) are reserved for customers.
//

#define KERNELPATCHDLL_IOCTL_BASE	0x800

//
// The device driver IOCTLs
//

#define CTL_CODE_KERNELPATCHDLL(i) CTL_CODE(FILE_DEVICE_KERNELPATCHDLL, KERNELPATCHDLL_IOCTL_BASE+i, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_KERNELPATCHDLL_HELLO	CTL_CODE_KERNELPATCHDLL(0)
#define IOCTL_KERNELPATCHDLL_TEST	CTL_CODE_KERNELPATCHDLL(1)

//
// Name that Win32 front end will use to open the KernelPatchDll device
//

#define KERNELPATCHDLL_WIN32_DEVICE_NAME_A	"\\\\.\\KernelPatchDll"
#define KERNELPATCHDLL_WIN32_DEVICE_NAME_W	L"\\\\.\\KernelPatchDll"
#define KERNELPATCHDLL_DEVICE_NAME_A			"\\Device\\KernelPatchDll"
#define KERNELPATCHDLL_DEVICE_NAME_W			L"\\Device\\KernelPatchDll"
#define KERNELPATCHDLL_DOS_DEVICE_NAME_A		"\\DosDevices\\KernelPatchDll"
#define KERNELPATCHDLL_DOS_DEVICE_NAME_W		L"\\DosDevices\\KernelPatchDll"

#ifdef _UNICODE
#define KERNELPATCHDLL_WIN32_DEVICE_NAME KERNELPATCHDLL_WIN32_DEVICE_NAME_W
#define KERNELPATCHDLL_DEVICE_NAME		KERNELPATCHDLL_DEVICE_NAME_W
#define KERNELPATCHDLL_DOS_DEVICE_NAME	KERNELPATCHDLL_DOS_DEVICE_NAME_W
#else
#define KERNELPATCHDLL_WIN32_DEVICE_NAME KERNELPATCHDLL_WIN32_DEVICE_NAME_A
#define KERNELPATCHDLL_DEVICE_NAME		KERNELPATCHDLL_DEVICE_NAME_A
#define KERNELPATCHDLL_DOS_DEVICE_NAME	KERNELPATCHDLL_DOS_DEVICE_NAME_A
#endif

#endif