/*

  KernelInjet.H

  Author: <your name>
  Last Updated: 2006-02-12

  This framework is generated by EasySYS 0.3.0
  This template file is copying from QuickSYS 0.3.0 written by Chunhua Liu

*/

#ifndef _KERNELINJET_H
#define _KERNELINJET_H 1

//
// Define the various device type values.  Note that values used by Microsoft
// Corporation are in the range 0-0x7FFF(32767), and 0x8000(32768)-0xFFFF(65535)
// are reserved for use by customers.
//

#define FILE_DEVICE_KERNELINJET	0x8000

//
// Macro definition for defining IOCTL and FSCTL function control codes. Note
// that function codes 0-0x7FF(2047) are reserved for Microsoft Corporation,
// and 0x800(2048)-0xFFF(4095) are reserved for customers.
//

#define KERNELINJET_IOCTL_BASE	0x800

//
// The device driver IOCTLs
//

#define CTL_CODE_KERNELINJET(i) CTL_CODE(FILE_DEVICE_KERNELINJET, KERNELINJET_IOCTL_BASE+i, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_KERNELINJET_HELLO	CTL_CODE_KERNELINJET(0)
#define IOCTL_KERNELINJET_TEST	CTL_CODE_KERNELINJET(1)

//
// Name that Win32 front end will use to open the KernelInjet device
//

#define KERNELINJET_WIN32_DEVICE_NAME_A	"\\\\.\\KernelInjet"
#define KERNELINJET_WIN32_DEVICE_NAME_W	L"\\\\.\\KernelInjet"
#define KERNELINJET_DEVICE_NAME_A			"\\Device\\KernelInjet"
#define KERNELINJET_DEVICE_NAME_W			L"\\Device\\KernelInjet"
#define KERNELINJET_DOS_DEVICE_NAME_A		"\\DosDevices\\KernelInjet"
#define KERNELINJET_DOS_DEVICE_NAME_W		L"\\DosDevices\\KernelInjet"

#ifdef _UNICODE
#define KERNELINJET_WIN32_DEVICE_NAME KERNELINJET_WIN32_DEVICE_NAME_W
#define KERNELINJET_DEVICE_NAME		KERNELINJET_DEVICE_NAME_W
#define KERNELINJET_DOS_DEVICE_NAME	KERNELINJET_DOS_DEVICE_NAME_W
#else
#define KERNELINJET_WIN32_DEVICE_NAME KERNELINJET_WIN32_DEVICE_NAME_A
#define KERNELINJET_DEVICE_NAME		KERNELINJET_DEVICE_NAME_A
#define KERNELINJET_DOS_DEVICE_NAME	KERNELINJET_DOS_DEVICE_NAME_A
#endif

#endif