/*

  IrpHook.H

  Author: <your name>
  Last Updated: 2006-02-12

  This framework is generated by EasySYS 0.3.0
  This template file is copying from QuickSYS 0.3.0 written by Chunhua Liu

*/

#ifndef _IRPHOOK_H
#define _IRPHOOK_H 1

//
// Define the various device type values.  Note that values used by Microsoft
// Corporation are in the range 0-0x7FFF(32767), and 0x8000(32768)-0xFFFF(65535)
// are reserved for use by customers.
//

#define FILE_DEVICE_IRPHOOK	0x8000

//
// Macro definition for defining IOCTL and FSCTL function control codes. Note
// that function codes 0-0x7FF(2047) are reserved for Microsoft Corporation,
// and 0x800(2048)-0xFFF(4095) are reserved for customers.
//

#define IRPHOOK_IOCTL_BASE	0x800

//
// The device driver IOCTLs
//

#define CTL_CODE_IRPHOOK(i) CTL_CODE(FILE_DEVICE_IRPHOOK, IRPHOOK_IOCTL_BASE+i, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_IRPHOOK_HELLO	CTL_CODE_IRPHOOK(0)
#define IOCTL_IRPHOOK_TEST	CTL_CODE_IRPHOOK(1)

//
// Name that Win32 front end will use to open the IrpHook device
//

#define IRPHOOK_WIN32_DEVICE_NAME_A	"\\\\.\\IrpHook"
#define IRPHOOK_WIN32_DEVICE_NAME_W	L"\\\\.\\IrpHook"
#define IRPHOOK_DEVICE_NAME_A			"\\Device\\IrpHook"
#define IRPHOOK_DEVICE_NAME_W			L"\\Device\\IrpHook"
#define IRPHOOK_DOS_DEVICE_NAME_A		"\\DosDevices\\IrpHook"
#define IRPHOOK_DOS_DEVICE_NAME_W		L"\\DosDevices\\IrpHook"

#ifdef _UNICODE
#define IRPHOOK_WIN32_DEVICE_NAME IRPHOOK_WIN32_DEVICE_NAME_W
#define IRPHOOK_DEVICE_NAME		IRPHOOK_DEVICE_NAME_W
#define IRPHOOK_DOS_DEVICE_NAME	IRPHOOK_DOS_DEVICE_NAME_W
#else
#define IRPHOOK_WIN32_DEVICE_NAME IRPHOOK_WIN32_DEVICE_NAME_A
#define IRPHOOK_DEVICE_NAME		IRPHOOK_DEVICE_NAME_A
#define IRPHOOK_DOS_DEVICE_NAME	IRPHOOK_DOS_DEVICE_NAME_A
#endif

#endif