/*-----------------------------------------------------------------------
第13章  Hook技术
《加密与解密（第四版）》
(c)  看雪学院 www.kanxue.com 2000-2018
-----------------------------------------------------------------------*/


/*

  IrpHook.C

  Author: achillis
  Last Updated: 2006-03-23

  This framework is generated by EasySYS 0.3.0
  This template file is copying from QuickSYS 0.3.0 written by Chunhua Liu

*/

#include "dbghelp.h"
#include "IrpHook.h"
#include "ntifs.h"
#include "myKernel.h"

// Device driver routine declarations.
//

VOID
FASTCALL
My_IofCompleteRequest(
	IN PIRP Irp,
	IN CCHAR PriorityBoost
    );

typedef VOID
(FASTCALL *PFN_IofCompleteRequest)(
	IN PIRP Irp,
	IN CCHAR PriorityBoost
    );

NTSTATUS
DriverEntry(
	IN PDRIVER_OBJECT		DriverObject,
	IN PUNICODE_STRING		RegistryPath
	);

NTSTATUS
IrphookDispatchCreate(
	IN PDEVICE_OBJECT		DeviceObject,
	IN PIRP					Irp
	);

NTSTATUS
IrphookDispatchClose(
	IN PDEVICE_OBJECT		DeviceObject,
	IN PIRP					Irp
	);

NTSTATUS
IrphookDispatchDeviceControl(
	IN PDEVICE_OBJECT		DeviceObject,
	IN PIRP					Irp
	);

VOID
IrphookUnload(
	IN PDRIVER_OBJECT		DriverObject
	);

BOOL InstallIrpHook();
VOID UnInstallIrpHook();

#ifdef ALLOC_PRAGMA
#pragma alloc_text(INIT, DriverEntry)
#pragma alloc_text(PAGE, IrphookDispatchCreate)
#pragma alloc_text(PAGE, IrphookDispatchClose)
#pragma alloc_text(PAGE, IrphookDispatchDeviceControl)
#pragma alloc_text(PAGE, IrphookUnload)
#endif // ALLOC_PRAGMA

//实际修改位置的指针
ULONG* g_pIofCompleteRequest = NULL;
PFN_IofCompleteRequest OriginalIofCompleteRequest = NULL ;

NTSTATUS
DriverEntry(
	IN PDRIVER_OBJECT		DriverObject,
	IN PUNICODE_STRING		RegistryPath
	)
{
	//
    // Create dispatch points for device control, create, close.
    //

    DriverObject->MajorFunction[IRP_MJ_CREATE]         = IrphookDispatchCreate;
    DriverObject->MajorFunction[IRP_MJ_CLOSE]          = IrphookDispatchClose;
    DriverObject->MajorFunction[IRP_MJ_DEVICE_CONTROL] = IrphookDispatchDeviceControl;
    DriverObject->DriverUnload                         = IrphookUnload;
	
	InstallIrpHook();
	DbgPrint("[IrpHook] Loaded!\n");
    return STATUS_SUCCESS;
}

NTSTATUS
IrphookDispatchCreate(
	IN PDEVICE_OBJECT		DeviceObject,
	IN PIRP					Irp
	)
{
	NTSTATUS status = STATUS_SUCCESS;

    Irp->IoStatus.Information = 0;

	dprintf("[IrpHook] IRP_MJ_CREATE\n");

    Irp->IoStatus.Status = status;
    IoCompleteRequest(Irp, IO_NO_INCREMENT);

    return status;
}

NTSTATUS
IrphookDispatchClose(
	IN PDEVICE_OBJECT		DeviceObject,
	IN PIRP					Irp
	)
{
	NTSTATUS status = STATUS_SUCCESS;

    Irp->IoStatus.Information = 0;

	dprintf("[IrpHook] IRP_MJ_CLOSE\n");

    Irp->IoStatus.Status = status;
    IoCompleteRequest(Irp, IO_NO_INCREMENT);

    return status;
}

NTSTATUS
IrphookDispatchDeviceControl(
	IN PDEVICE_OBJECT		DeviceObject,
	IN PIRP					Irp
	)
{
	NTSTATUS status = STATUS_SUCCESS;
	Irp->IoStatus.Information = 0;

	dprintf("[IrpHook] IRP_MJ_DEVICE_CONTROL\n");

    Irp->IoStatus.Status = status;
    IoCompleteRequest(Irp, IO_NO_INCREMENT);

    return status;
}

VOID
IrphookUnload(
	IN PDRIVER_OBJECT		DriverObject
	)
{
	if (OriginalIofCompleteRequest != NULL)
	{
		UnInstallIrpHook();
		DbgPrint("[IrpHook] UnHooked.\n");
	}
    DbgPrint("[IrpHook] Unloaded\n");
}



BOOL InstallIrpHook()
{
	UNICODE_STRING usFuncName;
	BYTE *pfnIofCompleteRequest = 0 ;

	RtlInitUnicodeString(&usFuncName,L"IofCompleteRequest");
	pfnIofCompleteRequest = MmGetSystemRoutineAddress(&usFuncName);

	if (pfnIofCompleteRequest == NULL)
	{
		DbgPrint("Could not get address of IofCompleteRequest.\n");
		return FALSE;
	}

	//FF 25 xxxxxxxxx = jmp ds:[xxxxxxxxx]

	if (memcmp(pfnIofCompleteRequest,"\xFF\x25",2) != 0)
	{
		DbgPrint("IofCompleteRequest maybe already hooked.\n");
		return FALSE;
	}
	
	g_pIofCompleteRequest = (ULONG*)*(ULONG*)(pfnIofCompleteRequest+2);

	//Hook
	OriginalIofCompleteRequest = (PFN_IofCompleteRequest)InterlockedExchange((volatile LONG*)g_pIofCompleteRequest,(LONG)My_IofCompleteRequest);
	
	DbgPrint("[IrpHook] Hook IofCompleteRequest OK. Old = 0x%08X new = 0x%X\n",OriginalIofCompleteRequest,(ULONG)My_IofCompleteRequest);

	return TRUE;
}

VOID UnInstallIrpHook()
{
	InterlockedExchange((volatile LONG*)g_pIofCompleteRequest,(LONG)OriginalIofCompleteRequest);
}

VOID
FASTCALL
My_IofCompleteRequest(
	IN PIRP Irp,
	IN CCHAR PriorityBoost
    )
{
	char *szImageFileName = PsGetProcessImageFileName(PsGetCurrentProcess());
	DbgPrint("[%s] Complete Request. Irp = 0x%08X\n",szImageFileName,Irp);
	OriginalIofCompleteRequest(Irp,PriorityBoost);
}