/*

  ProcessNotifyInject.H

  Author: <your name>
  Last Updated: 2006-02-12

  This framework is generated by EasySYS 0.3.0
  This template file is copying from QuickSYS 0.3.0 written by Chunhua Liu

*/

#ifndef _PROCESSNOTIFYINJECT_H
#define _PROCESSNOTIFYINJECT_H 1

//
// Define the various device type values.  Note that values used by Microsoft
// Corporation are in the range 0-0x7FFF(32767), and 0x8000(32768)-0xFFFF(65535)
// are reserved for use by customers.
//

#define FILE_DEVICE_PROCESSNOTIFYINJECT	0x8000

//
// Macro definition for defining IOCTL and FSCTL function control codes. Note
// that function codes 0-0x7FF(2047) are reserved for Microsoft Corporation,
// and 0x800(2048)-0xFFF(4095) are reserved for customers.
//

#define PROCESSNOTIFYINJECT_IOCTL_BASE	0x800

//
// The device driver IOCTLs
//

#define CTL_CODE_PROCESSNOTIFYINJECT(i) CTL_CODE(FILE_DEVICE_PROCESSNOTIFYINJECT, PROCESSNOTIFYINJECT_IOCTL_BASE+i, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_PROCESSNOTIFYINJECT_HELLO	CTL_CODE_PROCESSNOTIFYINJECT(0)
#define IOCTL_PROCESSNOTIFYINJECT_TEST	CTL_CODE_PROCESSNOTIFYINJECT(1)

//
// Name that Win32 front end will use to open the ProcessNotifyInject device
//

#define PROCESSNOTIFYINJECT_WIN32_DEVICE_NAME_A	"\\\\.\\ProcessNotifyInject"
#define PROCESSNOTIFYINJECT_WIN32_DEVICE_NAME_W	L"\\\\.\\ProcessNotifyInject"
#define PROCESSNOTIFYINJECT_DEVICE_NAME_A			"\\Device\\ProcessNotifyInject"
#define PROCESSNOTIFYINJECT_DEVICE_NAME_W			L"\\Device\\ProcessNotifyInject"
#define PROCESSNOTIFYINJECT_DOS_DEVICE_NAME_A		"\\DosDevices\\ProcessNotifyInject"
#define PROCESSNOTIFYINJECT_DOS_DEVICE_NAME_W		L"\\DosDevices\\ProcessNotifyInject"

#ifdef _UNICODE
#define PROCESSNOTIFYINJECT_WIN32_DEVICE_NAME PROCESSNOTIFYINJECT_WIN32_DEVICE_NAME_W
#define PROCESSNOTIFYINJECT_DEVICE_NAME		PROCESSNOTIFYINJECT_DEVICE_NAME_W
#define PROCESSNOTIFYINJECT_DOS_DEVICE_NAME	PROCESSNOTIFYINJECT_DOS_DEVICE_NAME_W
#else
#define PROCESSNOTIFYINJECT_WIN32_DEVICE_NAME PROCESSNOTIFYINJECT_WIN32_DEVICE_NAME_A
#define PROCESSNOTIFYINJECT_DEVICE_NAME		PROCESSNOTIFYINJECT_DEVICE_NAME_A
#define PROCESSNOTIFYINJECT_DOS_DEVICE_NAME	PROCESSNOTIFYINJECT_DOS_DEVICE_NAME_A
#endif

#endif