/*

  KernelResumeInject.H

  Author: <your name>
  Last Updated: 2006-02-12

  This framework is generated by EasySYS 0.3.0
  This template file is copying from QuickSYS 0.3.0 written by Chunhua Liu

*/

#ifndef _KERNELRESUMEINJECT_H
#define _KERNELRESUMEINJECT_H 1

//
// Define the various device type values.  Note that values used by Microsoft
// Corporation are in the range 0-0x7FFF(32767), and 0x8000(32768)-0xFFFF(65535)
// are reserved for use by customers.
//

#define FILE_DEVICE_KERNELRESUMEINJECT	0x8000

//
// Macro definition for defining IOCTL and FSCTL function control codes. Note
// that function codes 0-0x7FF(2047) are reserved for Microsoft Corporation,
// and 0x800(2048)-0xFFF(4095) are reserved for customers.
//

#define KERNELRESUMEINJECT_IOCTL_BASE	0x800

//
// The device driver IOCTLs
//

#define CTL_CODE_KERNELRESUMEINJECT(i) CTL_CODE(FILE_DEVICE_KERNELRESUMEINJECT, KERNELRESUMEINJECT_IOCTL_BASE+i, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_KERNELRESUMEINJECT_HELLO	CTL_CODE_KERNELRESUMEINJECT(0)
#define IOCTL_KERNELRESUMEINJECT_TEST	CTL_CODE_KERNELRESUMEINJECT(1)

//
// Name that Win32 front end will use to open the KernelResumeInject device
//

#define KERNELRESUMEINJECT_WIN32_DEVICE_NAME_A	"\\\\.\\KernelResumeInject"
#define KERNELRESUMEINJECT_WIN32_DEVICE_NAME_W	L"\\\\.\\KernelResumeInject"
#define KERNELRESUMEINJECT_DEVICE_NAME_A			"\\Device\\KernelResumeInject"
#define KERNELRESUMEINJECT_DEVICE_NAME_W			L"\\Device\\KernelResumeInject"
#define KERNELRESUMEINJECT_DOS_DEVICE_NAME_A		"\\DosDevices\\KernelResumeInject"
#define KERNELRESUMEINJECT_DOS_DEVICE_NAME_W		L"\\DosDevices\\KernelResumeInject"

#ifdef _UNICODE
#define KERNELRESUMEINJECT_WIN32_DEVICE_NAME KERNELRESUMEINJECT_WIN32_DEVICE_NAME_W
#define KERNELRESUMEINJECT_DEVICE_NAME		KERNELRESUMEINJECT_DEVICE_NAME_W
#define KERNELRESUMEINJECT_DOS_DEVICE_NAME	KERNELRESUMEINJECT_DOS_DEVICE_NAME_W
#else
#define KERNELRESUMEINJECT_WIN32_DEVICE_NAME KERNELRESUMEINJECT_WIN32_DEVICE_NAME_A
#define KERNELRESUMEINJECT_DEVICE_NAME		KERNELRESUMEINJECT_DEVICE_NAME_A
#define KERNELRESUMEINJECT_DOS_DEVICE_NAME	KERNELRESUMEINJECT_DOS_DEVICE_NAME_A
#endif

#endif