NAME    EXAMPLE
DATA    SEGMENT
FIRST   DW  6CD5H
SECOND  DW  01F8H
THIRD1  DW ?
THIRD2  DW  2 DUP (?)
DATA    ENDS
STACK   SEGMENT  STACK  
        DW  256 DUP (?)
STACK   ENDS
CODE    SEGMENT
        ASSUME  CS:CODE,DS:DATA,SS:STACK
START:  MOV  AX,DATA
        MOV  DS,AX
        MOV  AX,FIRST
        ADD  AX,SECOND
        MOV  THIRD1,AX
        MOV  AX,FIRST
        MUL  SECOND
        MOV  THIRD2,AX
        MOV  THIRD2+2,DX
        MOV  AH,4CH
        INT  21H
CODE    ENDS
        END  START
