/*

  ShadowSDTHook.H

  Author: <your name>
  Last Updated: 2006-02-12

  This framework is generated by EasySYS 0.3.0
  This template file is copying from QuickSYS 0.3.0 written by Chunhua Liu

*/

#ifndef _SHADOWSDTHOOK_H
#define _SHADOWSDTHOOK_H 1

//
// Define the various device type values.  Note that values used by Microsoft
// Corporation are in the range 0-0x7FFF(32767), and 0x8000(32768)-0xFFFF(65535)
// are reserved for use by customers.
//

#define FILE_DEVICE_SHADOWSDTHOOK	0x8000

//
// Macro definition for defining IOCTL and FSCTL function control codes. Note
// that function codes 0-0x7FF(2047) are reserved for Microsoft Corporation,
// and 0x800(2048)-0xFFF(4095) are reserved for customers.
//

#define SHADOWSDTHOOK_IOCTL_BASE	0x800

//
// The device driver IOCTLs
//

#define CTL_CODE_SHADOWSDTHOOK(i) CTL_CODE(FILE_DEVICE_SHADOWSDTHOOK, SHADOWSDTHOOK_IOCTL_BASE+i, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_SHADOWSDTHOOK_ENABLEPROT		CTL_CODE_SHADOWSDTHOOK(0)
#define IOCTL_SHADOWSDTHOOK_DISABLEPROT		CTL_CODE_SHADOWSDTHOOK(1)
#define IOCTL_SHADOWSDTHOOK_SETTRUSTPROC	CTL_CODE_SHADOWSDTHOOK(2)

//
// Name that Win32 front end will use to open the ShadowSDTHook device
//

#define SHADOWSDTHOOK_WIN32_DEVICE_NAME_A	"\\\\.\\ShadowSDTHook"
#define SHADOWSDTHOOK_WIN32_DEVICE_NAME_W	L"\\\\.\\ShadowSDTHook"
#define SHADOWSDTHOOK_DEVICE_NAME_A			"\\Device\\ShadowSDTHook"
#define SHADOWSDTHOOK_DEVICE_NAME_W			L"\\Device\\ShadowSDTHook"
#define SHADOWSDTHOOK_DOS_DEVICE_NAME_A		"\\DosDevices\\ShadowSDTHook"
#define SHADOWSDTHOOK_DOS_DEVICE_NAME_W		L"\\DosDevices\\ShadowSDTHook"

#ifdef _UNICODE
#define SHADOWSDTHOOK_WIN32_DEVICE_NAME SHADOWSDTHOOK_WIN32_DEVICE_NAME_W
#define SHADOWSDTHOOK_DEVICE_NAME		SHADOWSDTHOOK_DEVICE_NAME_W
#define SHADOWSDTHOOK_DOS_DEVICE_NAME	SHADOWSDTHOOK_DOS_DEVICE_NAME_W
#else
#define SHADOWSDTHOOK_WIN32_DEVICE_NAME SHADOWSDTHOOK_WIN32_DEVICE_NAME_A
#define SHADOWSDTHOOK_DEVICE_NAME		SHADOWSDTHOOK_DEVICE_NAME_A
#define SHADOWSDTHOOK_DOS_DEVICE_NAME	SHADOWSDTHOOK_DOS_DEVICE_NAME_A
#endif

#endif