/*

  IDTHook.H

  Author: <your name>
  Last Updated: 2006-02-12

  This framework is generated by EasySYS 0.3.0
  This template file is copying from QuickSYS 0.3.0 written by Chunhua Liu

*/

#ifndef _IDTHOOK_H
#define _IDTHOOK_H 1

//
// Define the various device type values.  Note that values used by Microsoft
// Corporation are in the range 0-0x7FFF(32767), and 0x8000(32768)-0xFFFF(65535)
// are reserved for use by customers.
//

#define FILE_DEVICE_IDTHOOK	0x8000

//
// Macro definition for defining IOCTL and FSCTL function control codes. Note
// that function codes 0-0x7FF(2047) are reserved for Microsoft Corporation,
// and 0x800(2048)-0xFFF(4095) are reserved for customers.
//

#define IDTHOOK_IOCTL_BASE	0x800

//
// The device driver IOCTLs
//

#define CTL_CODE_IDTHOOK(i) CTL_CODE(FILE_DEVICE_IDTHOOK, IDTHOOK_IOCTL_BASE+i, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_IDTHOOK_HELLO	CTL_CODE_IDTHOOK(0)
#define IOCTL_IDTHOOK_TEST	CTL_CODE_IDTHOOK(1)

//
// Name that Win32 front end will use to open the IDTHook device
//

#define IDTHOOK_WIN32_DEVICE_NAME_A	"\\\\.\\IDTHook"
#define IDTHOOK_WIN32_DEVICE_NAME_W	L"\\\\.\\IDTHook"
#define IDTHOOK_DEVICE_NAME_A			"\\Device\\IDTHook"
#define IDTHOOK_DEVICE_NAME_W			L"\\Device\\IDTHook"
#define IDTHOOK_DOS_DEVICE_NAME_A		"\\DosDevices\\IDTHook"
#define IDTHOOK_DOS_DEVICE_NAME_W		L"\\DosDevices\\IDTHook"

#ifdef _UNICODE
#define IDTHOOK_WIN32_DEVICE_NAME IDTHOOK_WIN32_DEVICE_NAME_W
#define IDTHOOK_DEVICE_NAME		IDTHOOK_DEVICE_NAME_W
#define IDTHOOK_DOS_DEVICE_NAME	IDTHOOK_DOS_DEVICE_NAME_W
#else
#define IDTHOOK_WIN32_DEVICE_NAME IDTHOOK_WIN32_DEVICE_NAME_A
#define IDTHOOK_DEVICE_NAME		IDTHOOK_DEVICE_NAME_A
#define IDTHOOK_DOS_DEVICE_NAME	IDTHOOK_DOS_DEVICE_NAME_A
#endif

#endif