/*

  FSDHook.H

  Author: <your name>
  Last Updated: 2006-02-12

  This framework is generated by EasySYS 0.3.0
  This template file is copying from QuickSYS 0.3.0 written by Chunhua Liu

*/

#ifndef _FSDHOOK_H
#define _FSDHOOK_H 1

//
// Define the various device type values.  Note that values used by Microsoft
// Corporation are in the range 0-0x7FFF(32767), and 0x8000(32768)-0xFFFF(65535)
// are reserved for use by customers.
//

#define FILE_DEVICE_FSDHOOK	0x8000

//
// Macro definition for defining IOCTL and FSCTL function control codes. Note
// that function codes 0-0x7FF(2047) are reserved for Microsoft Corporation,
// and 0x800(2048)-0xFFF(4095) are reserved for customers.
//

#define FSDHOOK_IOCTL_BASE	0x800

//
// The device driver IOCTLs
//

#define CTL_CODE_FSDHOOK(i) CTL_CODE(FILE_DEVICE_FSDHOOK, FSDHOOK_IOCTL_BASE+i, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_FSDHOOK_HELLO	CTL_CODE_FSDHOOK(0)
#define IOCTL_FSDHOOK_TEST	CTL_CODE_FSDHOOK(1)

//
// Name that Win32 front end will use to open the FSDHook device
//

#define FSDHOOK_WIN32_DEVICE_NAME_A	"\\\\.\\FSDHook"
#define FSDHOOK_WIN32_DEVICE_NAME_W	L"\\\\.\\FSDHook"
#define FSDHOOK_DEVICE_NAME_A			"\\Device\\FSDHook"
#define FSDHOOK_DEVICE_NAME_W			L"\\Device\\FSDHook"
#define FSDHOOK_DOS_DEVICE_NAME_A		"\\DosDevices\\FSDHook"
#define FSDHOOK_DOS_DEVICE_NAME_W		L"\\DosDevices\\FSDHook"

#ifdef _UNICODE
#define FSDHOOK_WIN32_DEVICE_NAME FSDHOOK_WIN32_DEVICE_NAME_W
#define FSDHOOK_DEVICE_NAME		FSDHOOK_DEVICE_NAME_W
#define FSDHOOK_DOS_DEVICE_NAME	FSDHOOK_DOS_DEVICE_NAME_W
#else
#define FSDHOOK_WIN32_DEVICE_NAME FSDHOOK_WIN32_DEVICE_NAME_A
#define FSDHOOK_DEVICE_NAME		FSDHOOK_DEVICE_NAME_A
#define FSDHOOK_DOS_DEVICE_NAME	FSDHOOK_DOS_DEVICE_NAME_A
#endif

#endif