/*

  KeLoad.H

  Author: <your name>
  Last Updated: 2006-02-12

  This framework is generated by EasySYS 0.3.0
  This template file is copying from QuickSYS 0.3.0 written by Chunhua Liu

*/

#ifndef _KELOAD_H
#define _KELOAD_H 1

//
// Define the various device type values.  Note that values used by Microsoft
// Corporation are in the range 0-0x7FFF(32767), and 0x8000(32768)-0xFFFF(65535)
// are reserved for use by customers.
//

#define FILE_DEVICE_KELOAD	0x8000

//
// Macro definition for defining IOCTL and FSCTL function control codes. Note
// that function codes 0-0x7FF(2047) are reserved for Microsoft Corporation,
// and 0x800(2048)-0xFFF(4095) are reserved for customers.
//

#define KELOAD_IOCTL_BASE	0x800

//
// The device driver IOCTLs
//

#define CTL_CODE_KELOAD(i) CTL_CODE(FILE_DEVICE_KELOAD, KELOAD_IOCTL_BASE+i, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_KELOAD_HELLO	CTL_CODE_KELOAD(0)
#define IOCTL_KELOAD_TEST	CTL_CODE_KELOAD(1)

//
// Name that Win32 front end will use to open the KeLoad device
//

#define KELOAD_WIN32_DEVICE_NAME_A	"\\\\.\\KeLoad"
#define KELOAD_WIN32_DEVICE_NAME_W	L"\\\\.\\KeLoad"
#define KELOAD_DEVICE_NAME_A			"\\Device\\KeLoad"
#define KELOAD_DEVICE_NAME_W			L"\\Device\\KeLoad"
#define KELOAD_DOS_DEVICE_NAME_A		"\\DosDevices\\KeLoad"
#define KELOAD_DOS_DEVICE_NAME_W		L"\\DosDevices\\KeLoad"

#ifdef _UNICODE
#define KELOAD_WIN32_DEVICE_NAME KELOAD_WIN32_DEVICE_NAME_W
#define KELOAD_DEVICE_NAME		KELOAD_DEVICE_NAME_W
#define KELOAD_DOS_DEVICE_NAME	KELOAD_DOS_DEVICE_NAME_W
#else
#define KELOAD_WIN32_DEVICE_NAME KELOAD_WIN32_DEVICE_NAME_A
#define KELOAD_DEVICE_NAME		KELOAD_DEVICE_NAME_A
#define KELOAD_DOS_DEVICE_NAME	KELOAD_DOS_DEVICE_NAME_A
#endif

#endif