/*

  AntiDllInject.H

  Author: <your name>
  Last Updated: 2006-02-12

  This framework is generated by EasySYS 0.3.0
  This template file is copying from QuickSYS 0.3.0 written by Chunhua Liu

*/

#ifndef _ANTIDLLINJECT_H
#define _ANTIDLLINJECT_H 1

//
// Define the various device type values.  Note that values used by Microsoft
// Corporation are in the range 0-0x7FFF(32767), and 0x8000(32768)-0xFFFF(65535)
// are reserved for use by customers.
//

#define FILE_DEVICE_ANTIDLLINJECT	0x8000

//
// Macro definition for defining IOCTL and FSCTL function control codes. Note
// that function codes 0-0x7FF(2047) are reserved for Microsoft Corporation,
// and 0x800(2048)-0xFFF(4095) are reserved for customers.
//

#define ANTIDLLINJECT_IOCTL_BASE	0x800

//
// The device driver IOCTLs
//

#define CTL_CODE_ANTIDLLINJECT(i) CTL_CODE(FILE_DEVICE_ANTIDLLINJECT, ANTIDLLINJECT_IOCTL_BASE+i, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_ANTIDLLINJECT_HELLO	CTL_CODE_ANTIDLLINJECT(0)
#define IOCTL_ANTIDLLINJECT_TEST	CTL_CODE_ANTIDLLINJECT(1)

//
// Name that Win32 front end will use to open the AntiDllInject device
//

#define ANTIDLLINJECT_WIN32_DEVICE_NAME_A	"\\\\.\\AntiDllInject"
#define ANTIDLLINJECT_WIN32_DEVICE_NAME_W	L"\\\\.\\AntiDllInject"
#define ANTIDLLINJECT_DEVICE_NAME_A			"\\Device\\AntiDllInject"
#define ANTIDLLINJECT_DEVICE_NAME_W			L"\\Device\\AntiDllInject"
#define ANTIDLLINJECT_DOS_DEVICE_NAME_A		"\\DosDevices\\AntiDllInject"
#define ANTIDLLINJECT_DOS_DEVICE_NAME_W		L"\\DosDevices\\AntiDllInject"

#ifdef _UNICODE
#define ANTIDLLINJECT_WIN32_DEVICE_NAME ANTIDLLINJECT_WIN32_DEVICE_NAME_W
#define ANTIDLLINJECT_DEVICE_NAME		ANTIDLLINJECT_DEVICE_NAME_W
#define ANTIDLLINJECT_DOS_DEVICE_NAME	ANTIDLLINJECT_DOS_DEVICE_NAME_W
#else
#define ANTIDLLINJECT_WIN32_DEVICE_NAME ANTIDLLINJECT_WIN32_DEVICE_NAME_A
#define ANTIDLLINJECT_DEVICE_NAME		ANTIDLLINJECT_DEVICE_NAME_A
#define ANTIDLLINJECT_DOS_DEVICE_NAME	ANTIDLLINJECT_DOS_DEVICE_NAME_A
#endif

#endif